name: esbuild-coffeescript Build

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node and cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CI
        run: pnpm run ci
